### ISSUE TITLE
Migrate banners.js

### ISSUE THREAD

**Issue by BobbyTheCatfish** [LDS-Gamers-Studios/icarus5.5#41]
ok this one is more of a new idea but it should have been in i5. Super easy to update.

Lines: 33
Utils/APIs: none
Snowflakes: yes
Feature request: we can't use discord links anymore so we'll have to store the pics locally

**Comment by BephneSniffer** [comment]
I assigned myself to this because I'm guessing that's how I let people know I'm trying to complete this migrate

**Comment by BobbyTheCatfish** [comment]
Closed by #73
