### ISSUE TITLE
migrate dice.js

### ISSUE THREAD

**Issue by BobbyTheCatfish** [LDS-Gamers-Studios/icarus5.5#78]
- move to fun.js
- !roll => /fun roll dice: int, sides: int, modifier: int

**Comment by j-romchain** [comment]
I may not finish working on it, but I am starting.

**Comment by j-romchain** [comment]
are we getting rid of ability to roll fate dice?

**Comment by j-romchain** [comment]
are we also getting rid of the ability to add multiple different sided rolls together like !roll 1d6+2d120

**Comment by j-romchain** [comment]
alternatively I could make 3 commands. roll rollf and rollOld. rollOld would keep the same syntax as !roll through a single string argument, roll would just run rollOld with 3 int arguments substituted in to the format, and rollf would just run rollOld with the arguments substituted in to the format for fate dice

**Comment by j-romchain** [comment]
I've completed that but I actually trimmed down /fun roll and /fun rollf instead of making them just call rollold like I proposed. I'll make a pull request for it with the rest of fun.js when I get that all sorted out.

**Comment by BobbyTheCatfish** [comment]
> are we getting rid of ability to roll fate dice?

I honestly didn't realize this was a thing lol. It hasn't been used for 3 years so I'd say its not a huge priority for us to keep it


> are we also getting rid of the ability to add multiple different sided rolls together like !roll 1d6+2d120

for the sake of simplicity, yeah.
