### ISSUE TITLE
migrate fun.js

### ISSUE THREAD

**Issue by BobbyTheCatfish** [LDS-Gamers-Studios/icarus5.5#80]
- make everything that can be a tag a tag
- !8ball => /fun 8ball
- !acronym => /fun acronym
- !allthe can prob be made static
- !color => /fun color, add a random color option if left blank
- !hbs => /fun hbs
- !hug has been tagged over
- !minesweeper can be removed
- not sure that we still need the recycle => star feature in memes

**Comment by j-romchain** [comment]
I did this. I did all of them anyway, I can disable any if you wish, but unless told otherwise I'm adding them anyway.

**Comment by BobbyTheCatfish** [comment]
but you _were_ told otherwise, in the top comment.

**Comment by j-romchain** [comment]
ok, code can be removed really easily, and I had fun writing them, and besides
"!hug has been tagged over
!minesweeper can be removed"
doesn't explicitly tell me that I can't add them anyway, just that I can get away with not adding them. but potato potato. if I need to put them on a branch of my own and remove them for the pull request to go through then so be it.
